spring:
  config:
    import: optional:env.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/passwordmanagerdb
    username: postgres
    password: qwerty
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mail:
    host: smtp.mail.com
    port: 465
    username: user@mail.com
    password: password
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
springdoc:
  paths-to-match: /api/v1/**
dbsecretkey: my-secret-key