###
# @no-log
# @name SignIn
POST http://localhost:8080/api/v1/authorization/signin
Content-Type: application/json

{
  "username": "first@mail.com",
  "password": "123456"
}

> {% client.global.set("auth_token", response.body); %}
###

###
# @no-log
# @name SignIn with wrong email
POST http://localhost:8080/api/v1/authorization/signin
Content-Type: application/json

{
  "username": "lorem@mail.com",
  "password": "123456"
}

> {% client.global.set("auth_token", response.body); %}
###

###
# @no-log
# @name SignUp
POST http://localhost:8080/api/v1/authorization/signup
Content-Type: application/json

{
  "username": "ghost777t@ya.ru",
  "password": "123456"
}
###

###
# @no-log
# @name SignIn
POST http://localhost:8080/api/v1/authorization/signin
Content-Type: application/json

{
  "username": "first@mail.com",
  "password": "123456"
}

> {% client.global.set("auth_token", response.body); %}
###

###
# @no-log
# @name Confirm email
GET http://localhost:8080/api/v1/authorization/confirmemail/91dc92b7-00f8-4bd8-8128-fa23fbd4462c
###

###
# @no-log
# @name User page
GET http://localhost:8080/user
Authorization: Bearer {{auth_token}}
###

###
# @no-log
# @name Admin page
GET http://localhost:8080/admin
Authorization: Bearer {{auth_token}}
###

###
# @no-log
# @name Get email
GET http://localhost:8080/api/v1/authorization/signin
Authorization: Bearer {{auth_token}}
###

###
# @no-log
# @name Change password
POST http://localhost:8080/api/v1/authorization/changepassword
Content-Type: application/json

{
  "loginRequest": {
    "username": "qwerty@mail.com",
    "password": "123456"
  },
  "newPassword": "qwerty"
}
###

###
# @no-log
# @name Change email
POST http://localhost:8080/api/v1/authorization/changeemail
Content-Type: application/json

{
  "loginRequest": {
    "username": "second@mail.com",
    "password": "123456"
  },
  "newEmail": "qwerty@mail.com"
}
###