###
# @no-log
# @name SignIn
POST http://localhost:8080/api/v1/authorization/signin
Content-Type: application/json

{
  "username": "first@mail.com",
  "password": "123456"
}

> {% client.global.set("auth_token", response.body); %}
###

###
# @no-log
# @name Get all passwords
GET http://localhost:8080/api/v1/savedpassword
Authorization: Bearer {{auth_token}}
###

###
# @no-log
# @name Get password by id
GET http://localhost:8080/api/v1/savedpassword/1
Authorization: Bearer {{auth_token}}
###

###
# @no-log
# @name Add new password
POST http://localhost:8080/api/v1/savedpassword
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "title": "Added password",
  "url": "http://localhost:8080",
  "username": "user",
  "password": "pass"
}
###

###
# @no-log
# @name Edit password
PUT http://localhost:8080/api/v1/savedpassword
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "id": 5,
  "title": "Added eee password"
}
###

###
# @no-log
# @name Delete password
DELETE http://localhost:8080/api/v1/savedpassword/5
Authorization: Bearer {{auth_token}}
###

###
# @no-log
# @name Add sharing to password
POST http://localhost:8080/api/v1/savedpassword/shared/5
Authorization: Bearer {{auth_token}}
Content-Type: application/json

"first@mail.com"

###

###
# @no-log
# @name Remove sharing to password
DELETE http://localhost:8080/api/v1/savedpassword/shared/5
Authorization: Bearer {{auth_token}}
Content-Type: application/json

"1"

###